/**
 * Architectural Decision Record (ADR) + constitution rule extraction and
 * commit-vs-spec drift detection.
 */

export type RuleSeverity = "hard" | "soft";

export type SpecRule = {
  id: string;
  source: string;
  text: string;
  severity: RuleSeverity;
  /** Path patterns that would violate this rule. */
  patterns: RegExp[];
  topics: string[];
};

export const RULE_SOURCE_RE =
  /(^|\/)(agents\.md|constitution\.md|claude\.md|\.cursorrules|llms\.txt)$|^docs\/adr\/.+\.md$|(^|\/)adr\/.+\.md$/i;

export function isRuleSource(path: string): boolean {
  return RULE_SOURCE_RE.test(path);
}

const HARD_RE = /\b(never|must not|must never|do not|don't|forbidden|prohibited|banned|no longer|shall not)\b/i;
const SOFT_RE = /\b(must|should not|shouldn't|always|required|only|avoid|prefer)\b/i;

/** keyword -> offending path signature */
const TOPIC_MAP: { topic: string; kw: RegExp; path: RegExp }[] = [
  { topic: "backend", kw: /\b(backend|server-side|express|node server|api server|zero-backend|serverless)\b/i, path: /(^|\/)(api|server|backend|functions)\//i },
  { topic: "database", kw: /\b(database|sql|migration|postgres|supabase)\b/i, path: /(^|\/)(migrations?|db|database)\//i },
  { topic: "tests", kw: /\b(test|coverage|spec file|vitest|jest)\b/i, path: /\.(test|spec)\.[jt]sx?$/i },
  { topic: "dependencies", kw: /\b(dependency|dependencies|package|npm install|third-party)\b/i, path: /(^|\/)(package(-lock)?\.json|bun\.lockb?|yarn\.lock|pnpm-lock\.yaml)$/i },
  { topic: "config", kw: /\b(config|configuration|env|secret|credential)\b/i, path: /(\.env|config\.[jt]s|\.ya?ml)$/i },
  { topic: "styling", kw: /\b(inline style|css|tailwind|design token|hardcoded color)\b/i, path: /\.(css|scss)$/i },
  { topic: "generated", kw: /\b(generated|do not edit|autogenerated)\b/i, path: /(gen|generated)\.[jt]sx?$/i },
  { topic: "docs", kw: /\b(documentation|changelog|readme)\b/i, path: /(^|\/)(CHANGELOG|README)\.md$/i },
  { topic: "ci", kw: /\b(ci|workflow|github action|pipeline)\b/i, path: /(^|\/)\.github\/workflows\//i },
];

function globToRe(glob: string): RegExp | null {
  if (!/[/.*]/.test(glob) || glob.length > 60 || /\s/.test(glob)) return null;
  const esc = glob.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "§").replace(/\*/g, "[^/]*").replace(/§/g, ".*");
  try {
    return new RegExp(esc.startsWith("/") ? `${esc.slice(1)}` : `(^|/)${esc}`, "i");
  } catch {
    return null;
  }
}

/** Extracts non-negotiable rule statements from a spec / ADR document. */
export function extractRules(source: string, md: string): SpecRule[] {
  const out: SpecRule[] = [];
  const lines = (md ?? "").replace(/\r\n/g, "\n").split("\n");
  let inFence = false;
  let n = 0;
  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith("```")) {
      inFence = !inFence;
      continue;
    }
    if (inFence || line.length < 12 || line.length > 320) continue;
    const body = line.replace(/^([-*+]|\d+\.)\s+/, "").replace(/^#{1,6}\s+/, "").trim();
    const hard = HARD_RE.test(body);
    if (!hard && !SOFT_RE.test(body)) continue;

    const topics: string[] = [];
    const patterns: RegExp[] = [];
    for (const t of TOPIC_MAP) {
      if (t.kw.test(body)) {
        topics.push(t.topic);
        patterns.push(t.path);
      }
    }
    for (const m of body.matchAll(/`([^`\n]{2,60})`/g)) {
      const re = globToRe(m[1].trim());
      if (re) patterns.push(re);
    }
    if (!patterns.length) continue;
    out.push({
      id: `${source}#${n++}`,
      source,
      text: body.replace(/[*_`]/g, "").slice(0, 300),
      severity: hard ? "hard" : "soft",
      patterns,
      topics,
    });
  }
  return out.slice(0, 60);
}

export type CommitRecord = {
  sha: string;
  message: string;
  author: string;
  date: string;
  url: string;
  files: string[];
};

export type DriftFinding = {
  id: string;
  rule: SpecRule;
  commit: CommitRecord;
  file: string;
};

/** Cross-references changed files in recent commits against extracted rules. */
export function detectDrift(rules: SpecRule[], commits: CommitRecord[]): DriftFinding[] {
  const out: DriftFinding[] = [];
  const seen = new Set<string>();
  for (const c of commits) {
    for (const f of c.files) {
      for (const r of rules) {
        if (!r.patterns.some((p) => p.test(f))) continue;
        const key = `${r.id}|${f}`;
        if (seen.has(key)) continue;
        seen.add(key);
        out.push({ id: `${c.sha}|${key}`, rule: r, commit: c, file: f });
      }
    }
  }
  return out.sort((a, b) => (a.rule.severity === b.rule.severity ? 0 : a.rule.severity === "hard" ? -1 : 1));
}